# Config doc: https://docs.crawlab.cn/en/Config/ 
# Option meaning:
# "Y" -> yes
# "N" -> no
version: '3.3'
services:
  master:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: master
    environment:
      CRAWLAB_SERVER_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo" 
      CRAWLAB_REDIS_ADDRESS: "redis"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    volumes:
      - "./docker/crawlab/logs:/var/logs/crawlab"
  worker:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: worker
    environment:
      CRAWLAB_SERVER_MASTER: "N"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_REDIS_ADDRESS: "redis"
    depends_on:
      - mongo
      - redis
    volumes:
      - "./docker/crawlab/logs:/var/logs/crawlab"
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "./docker/mongo/data/db:/data/db"
    ports:
      - "10010:27017"
  redis:
    image: redis:latest
    restart: always
    volumes:
      - "./docker/redis/data:/data"  # make data persistent 持久化
    ports:
      - "10020:6379"
